export const STABLESWAP_POOLIDX = 1;
export const WEIGHTED_POOLIDX = 2;
export const METASTABLE_POOLIDX = 3;

export const POOLID = {
  WEIGHTED: WEIGHTED_POOLIDX,
  STABLE: STABLESWAP_POOLIDX,
  METASTABLE: METASTABLE_POOLIDX,
};
