export enum LOCAL_STORAGE_KEYS {
  SLIPPAGE_TOLERANCE_TYPE = "SLIPPAGE_TOLERANCE_TYPE",
  SLIPPAGE_TOLERANCE_VALUE = "SLIPPAGE_TOLERANCE_VALUE",
  DEADLINE_TYPE = "DEADLINE_TYPE",
  DEADLINE_VALUE = "DEADLINE_VALUE",
}

export const DEFAULT_DEADLINE = 30; // minutes
export const DEFAULT_SLIPPAGE = 1; // 0.3%
export const DEFAULT_SOUND_ENABLED = true; // 1 if true, 0 if false

enum POLLING {
  FAST = 10000,
  NORMAL = 20000,
  SLOW = 200000,
}
