export enum LOCAL_STORAGE_KEYS {
  CONNECTOR_ID = "CONNECTOR_ID",
  SLIPPAGE_TOLERANCE_TYPE = "SLIPPAGE_TOLERANCE_TYPE",
  SLIPPAGE_TOLERANCE_VALUE = "SLIPPAGE_TOLERANCE_VALUE",
  TRANSACTION_TYPE = "TRANSACTION_TYPE",
  DEADLINE_TYPE = "DEADLINE_TYPE",
  DEADLINE_VALUE = "DEADLINE_VALUE",
  USE_SIGNATURES = "USE_SIGNATURES",
  SOUND_ENABLED = "SOUND_ENABLED",
}

export enum TRANSACTION_TYPES {
  LEGACY = "legacy",
  EIP_1559 = "eip1559",
}

export const DEFAULT_DEADLINE = 30; // minutes
export const DEFAULT_SLIPPAGE = 1; // 0.3%
export const DEFAULT_SOUND_ENABLED = true; // 1 if true, 0 if false

export enum POLLING {
  FAST = 10000,
  NORMAL = 20000,
  SLOW = 200000,
}
