export enum LOCAL_STORAGE_KEYS {
  CONNECTOR_ID = "wagmi.wallet",
  SLIPPAGE_TOLERANCE = "SLIPPAGE_TOLERANCE",
  TRANSACTION_TYPE = "TRANSACTION_TYPE",
  USE_SIGNATURES = "USE_SIGNATURES",
}

export enum POLLING {
  FAST = 5000,
  NORMAL = 10000,
  SLOW = 100000,
}
