packages:
  - apps/dex
  - apps/bgt-station
  - apps/honey
  - packages/config/*
  - packages/ui
  - packages/shared-ui
  - packages/berajs
  - packages/bera-router
  - packages/api
  - packages/proto
