packages:
  - packages/config/*
  - packages/beracrocswap
  - packages/graphql
  - packages/berajs
  - packages/wagmi
  - packages/proto
  - packages/ui
  - packages/shared-ui
  - apps/dex
  - apps/bgt-station
  - apps/honey
  - apps/lend
  - apps/perp
  - apps/faucet
  - apps/validator-clue
  - apps/ambassador
  - apps/ecosystem
  - apps/berajs-docs
