import { Tooltip } from "./tooltip";

export const ApyTooltip = ({ className }: { className?: string }) => {
  return <Tooltip text={apyTooltipText()} className={className} />;
};

export const apyTooltipText = () => {
  return (
    <>
      APY (Annual Percentage Yield) is calculated based on the fees and rewards{" "}
      <br />
      generated by this pool over the last 24 hours. The APY displayed is <br />
      algorithmic and subject to change. See additional disclaimers in the notes
      below.
    </>
  );
};

export const BribeApyTooltip = ({ className }: { className?: string }) => {
  return <Tooltip text={bribeApyTooltipText()} className={className} />;
};

export const bribeApyTooltipText = () => {
  return (
    <>
      APY (Annual Percentage Yield) is calculated based on the value of bribes{" "}
      <br />
      emitted from a validator over the last 24 hours. The APY displayed is{" "}
      <br />
      algorithmic and subject to change. See additional disclaimers in the notes
      below.
    </>
  );
};
