const { program } = require("commander");
const fs = require("fs");
const path = require("path");

program.argument("<env>");

program.parse();

const env = program.args[0];

console.log("Copying files", env);

fs.writeFileSync(
  ".env",
  `# This file was generated by the .scripts/set-env.js
# Do not modify this file directly
# Modify the .env.local file instead if you want to add secrets
# otherwise modify the commited files and run pnpm set-env again

######################################
######################################
######################################
#======== AUTO GENERATED FILE ========
######################################
######################################
######################################
 \n\n\n`,
  "utf-8",
  {
    flag: "w+",
  },
);
fs.appendFileSync(
  ".env",
  fs.readFileSync(path.resolve(process.cwd(), `.env.${env}`), "utf-8"),
  "utf-8",
);

fs.appendFileSync(
  ".env",
  `######################################
######################################
######################################
#======== AUTO GENERATED FILE ========
######################################
######################################
######################################`,
);
